# Generated by Django 5.0.6 on 2024-07-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedfertilizer',
            name='store_keeper',
        ),
    ]
